Export the script we use to make release source tarballs
crowell/modpagespeed pull request #1450
Opened 2016-12-16 14:16 UTC by morlovich

(this was tweaked slightly after the 34 release)

2016-12-16 15:07 UTC, jeffkaufman requested changes

2016-12-16 15:07 UTC, jeffkaufman commented on devel/create_distro_tarball.sh
> +  echo "examples of git_tag  would be 'master' or '1.11.33.4'"
Can you clarify that `git_tag` can be a branch, tag, or commit id?  Basically, anything you can pass to `checkout -b`.

2016-12-16 15:07 UTC, jeffkaufman commented on devel/create_distro_tarball.sh
> +  CHECKOUT_DIR=`mktemp -d`
can we swap the backtick command invocations for `$(...)`, here and below?

2016-12-16 15:07 UTC, jeffkaufman commented on devel/create_distro_tarball.sh
> +# branch this script with every release.
Can you change this to be more explicit?  Something like:

```
# Note that this is highly-version specific, and requires tweaks for every
# release as its dependencies change.  Always run the version of this
# script that's on the branch you're making a tarball for.
```

2016-12-16 15:07 UTC, jeffkaufman commented on devel/create_distro_tarball.sh
> +tar cj --dereference --exclude='.git' --exclude='.svn' --exclude='.hg' -f $TARBALL \
`--exclude='.svn' --exclude='.hg'` shouldn't be needed anymore now that all our dependencies are git.

2016-12-16 15:07 UTC, jeffkaufman commented on devel/create_distro_tarball.sh
> +    $DIR/src/url
Could we exclude the windows dlls that lintian was objecting to here as well?

2016-12-20 14:43 UTC, morlovich commented
I am going to re-do it starting with a merge off branch 33 one, I think.

2016-12-20 14:43 UTC, closed without merging